package sh.oso.servicenow.e2e;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import org.apache.kafka.common.config.ConfigDef;
import org.junit.jupiter.api.Test;
import sh.oso.servicenow.sink.SinkConfig;
import sh.oso.servicenow.source.SourceConfig;
import sh.oso.servicenow.source.TableSpec;

/**
 * Generates the property-by-property configuration reference pages of the docs site directly from
 * each connector's {@link ConfigDef}, so the published reference can never drift from the code.
 * Runs as part of the normal build (surefire, so also with {@code -DskipE2E}); the output is
 * deterministic, so an intentional configuration change shows up as a docs diff in the same commit
 * and CI fails when the regenerated pages are not committed.
 */
class ConfigDocsGeneratorTest {

    private static final Path OUT_DIR =
            Path.of(System.getProperty("repo.root", ".."))
                    .resolve("website/docs/reference/configuration");
    private static final String BANNER =
            "<!-- GENERATED by ConfigDocsGeneratorTest. Do not edit by hand. -->";
    private static final List<ConfigDef.Importance> IMPORTANCE_ORDER =
            List.of(
                    ConfigDef.Importance.HIGH,
                    ConfigDef.Importance.MEDIUM,
                    ConfigDef.Importance.LOW);
    private static final String ALIAS = "<alias>";
    private static final String TOPIC = "<topic>";
    private static final String USER_AGENT_PREFIX = "kafka-connect-servicenow/";

    @Test
    void generateConfigurationReferencePages() throws IOException {
        Files.createDirectories(OUT_DIR);

        String source =
                page(
                                "Source configuration",
                                "Generated configuration reference for the source connector.",
                                1,
                                "sh.oso.servicenow.source.ServiceNowSourceConnector",
                                "Source Connector",
                                "/connectors/source",
                                SourceConfig.configDef(),
                                """
                                Framework properties (`name`, `tasks.max`, converters, `errors.*`)
                                follow the standard
                                [Kafka Connect connector configuration](https://kafka.apache.org/documentation/#connectconfigs).
                                Each alias listed in `snow.tables` names its table and topic with the
                                per-table properties at the end of this page; there is no `topics`
                                property on the source.
                                """)
                        + perTableSection();
        write("source.md", source);

        String sink =
                page(
                                "Sink configuration",
                                "Generated configuration reference for the sink connector.",
                                2,
                                "sh.oso.servicenow.sink.ServiceNowSinkConnector",
                                "Sink Connector",
                                "/connectors/sink",
                                SinkConfig.configDef(),
                                """
                                Select input with the standard framework properties `topics` or
                                `topics.regex`. For a dead letter queue use `errors.tolerance=all`
                                with `errors.deadletterqueue.topic.name`. The shared `snow.*`
                                connection, authentication, HTTP, TLS and retry properties are the
                                same as the source connector's.
                                """)
                        + perTopicSection();
        write("sink.md", sink);

        assertThat(source)
                .contains(BANNER)
                .contains("### `snow.tables`")
                .contains("### `snow.url`")
                .contains("### `snow.table." + ALIAS + ".name`")
                .doesNotContain("### `snow.task.tables`");
        assertThat(sink)
                .contains(BANNER)
                .contains("### `snow.sink.routing.mode`")
                .contains("### `snow.sink.topic." + TOPIC + ".table`");
    }

    private static void write(String file, String content) throws IOException {
        Files.writeString(OUT_DIR.resolve(file), content);
    }

    private static String page(
            String title,
            String description,
            int position,
            String connectorClass,
            String guideLabel,
            String guidePath,
            ConfigDef configDef,
            String intro) {
        StringBuilder md = new StringBuilder();
        md.append("---\n")
                .append("title: \"")
                .append(title)
                .append("\"\n")
                .append("description: \"")
                .append(description)
                .append("\"\n")
                .append("sidebar_position: ")
                .append(position)
                .append("\n")
                .append("---\n\n")
                .append(BANNER)
                .append("\n\n")
                .append("# ")
                .append(title)
                .append("\n\n")
                .append("`")
                .append(connectorClass)
                .append("`\n\n")
                .append(
                        "Property-by-property reference generated from the connector's `ConfigDef`,")
                .append(" so it always matches the release you are running. Usage guide: [")
                .append(guideLabel)
                .append("](")
                .append(guidePath)
                .append(").\n");
        if (!intro.isBlank()) {
            md.append("\n").append(intro.strip()).append("\n");
        }
        for (ConfigDef.Importance importance : IMPORTANCE_ORDER) {
            List<ConfigDef.ConfigKey> keys =
                    documented(configDef).stream().filter(k -> k.importance == importance).toList();
            if (keys.isEmpty()) {
                continue;
            }
            md.append("\n## ").append(importanceHeading(importance)).append("\n");
            for (ConfigDef.ConfigKey key : keys) {
                md.append(renderProperty(key));
            }
        }
        return md.toString();
    }

    /** The per-alias keys, rendered once with the literal placeholder. */
    private static String perTableSection() {
        StringBuilder md = new StringBuilder();
        md.append("\n## Per-table properties (`snow.table.")
                .append(ALIAS)
                .append(".*`)\n\n")
                .append("Every alias listed in `snow.tables` is configured with these keys, with")
                .append(" `")
                .append(ALIAS)
                .append("` replaced by the alias (for example `snow.table.incident.name`).")
                .append(" They are defined per alias in the configuration group `")
                .append(TableSpec.group(ALIAS))
                .append("` and are validated and reported by `PUT /connector-plugins/")
                .append("{class}/config/validate` like any other key.\n");
        for (ConfigDef.ConfigKey key : byImportance(TableSpec.defFor(ALIAS))) {
            md.append(renderProperty(key));
        }
        return md.toString();
    }

    /** The per-topic routing key, rendered once with the literal placeholder. */
    private static String perTopicSection() {
        StringBuilder md = new StringBuilder();
        md.append("\n## Per-topic routing (`snow.sink.topic.")
                .append(TOPIC)
                .append(".table`)\n\n")
                .append(
                        "Under `snow.sink.routing.mode=topic_map` each input topic is mapped to its")
                .append(" target table with one key per topic, with `")
                .append(TOPIC)
                .append("` replaced by the Kafka topic name")
                .append(" (for example `snow.sink.topic.incident-updates.table`).\n");
        for (ConfigDef.ConfigKey key : byImportance(SinkConfig.topicDef(TOPIC))) {
            md.append(renderProperty(key));
        }
        return md.toString();
    }

    /** Documented keys in the ConfigDef's insertion order. */
    private static List<ConfigDef.ConfigKey> documented(ConfigDef configDef) {
        return configDef.configKeys().values().stream()
                .filter(k -> k.documentation == null || !k.documentation.startsWith("Internal"))
                .toList();
    }

    /** Documented keys by importance, then by the ConfigDef's insertion order (a stable sort). */
    private static List<ConfigDef.ConfigKey> byImportance(ConfigDef configDef) {
        return documented(configDef).stream()
                .sorted(Comparator.comparingInt(k -> IMPORTANCE_ORDER.indexOf(k.importance)))
                .toList();
    }

    private static String importanceHeading(ConfigDef.Importance importance) {
        return switch (importance) {
            case HIGH -> "High importance";
            case MEDIUM -> "Medium importance";
            case LOW -> "Low importance";
        };
    }

    private static String renderProperty(ConfigDef.ConfigKey key) {
        StringBuilder md = new StringBuilder();
        md.append("\n### `").append(key.name).append("`\n\n");
        if (key.documentation != null && !key.documentation.isBlank()) {
            md.append(mdx(key.documentation.strip())).append("\n\n");
        }
        md.append("- **Type:** ").append(key.type.name().toLowerCase()).append("\n");
        md.append("- **Default:** ").append(renderDefault(key)).append("\n");
        if (key.validator != null) {
            String valid = key.validator.toString();
            if (!valid.isBlank()) {
                md.append("- **Valid values:** ").append(mdx(valid)).append("\n");
            }
        }
        md.append("- **Importance:** ").append(key.importance.name().toLowerCase()).append("\n");
        return md.toString();
    }

    private static String renderDefault(ConfigDef.ConfigKey key) {
        if (!key.hasDefault()) {
            return "none (**required**)";
        }
        Object value = key.defaultValue;
        if (value == null) {
            return "null";
        }
        String rendered =
                value instanceof List<?> list
                        ? String.join(",", list.stream().map(String::valueOf).toList())
                        : String.valueOf(value);
        if (rendered.startsWith(USER_AGENT_PREFIX)) {
            // The user agent embeds the build version read from the jar manifest, which differs
            // between a reactor build and a packaged jar and changes on every release. Render a
            // placeholder so the committed reference stays stable.
            rendered = USER_AGENT_PREFIX + "<version>";
        }
        return rendered.isEmpty() ? "\"\" (empty)" : "`" + rendered + "`";
    }

    /**
     * MDX parses a bare {@code <placeholder>} as JSX and {@code {expression}} as JavaScript, so
     * both are escaped outside code spans. Code spans are literal in MDX and are left untouched.
     */
    static String mdx(String text) {
        String[] parts = text.split("`", -1);
        if (parts.length % 2 == 0) {
            return escape(text); // unbalanced backticks: no code spans to protect
        }
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            if (i > 0) {
                out.append('`');
            }
            out.append(i % 2 == 0 ? escape(parts[i]) : parts[i]);
        }
        return out.toString();
    }

    private static String escape(String text) {
        return text.replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("{", "&#123;")
                .replace("}", "&#125;");
    }
}
